FROM node:18-alpine

WORKDIR /app

COPY ../package*.json .

RUN npm install

COPY ../index.js .

COPY ../test ./test

RUN npm install -g npm@latest

RUN npm update

RUN npm install chai@4.3.7

RUN chown -R node:node /app

USER node

CMD [ "node", "index.js" ]
