name: CICD

on:
  push:
    branches:
      - "feature"

env:
  GCP_PROJECT_ID: "ntx-devops"
  GCP_REGION: "asia-southeast2"
  GCP_GAR_LOCATION: "asia-southeast2-docker.pkg.dev/ntx-devops/ntx-devops-repository"
  IMAGE_NAME: "ntx-node-app"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build -t ${{ env.GCP_GAR_LOCATION }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ env.GCP_GAR_LOCATION }}