name: CICD

on:
  push:
    branches:
      - feature

env:
  GCP_REGION: asia-southeast2
  GCP_REPO_NAME: ntx-app-repo
  DOCKER_IMAGE_NAME: ntx-node-app
  APP_NAME: $DOCKER_IMAGE_NAME
  
jobs:
  infra-gcp-terraform:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.NTX_GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.NTX_GCP_SA }}
        export_default_credentials: true

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Provision Infra With Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve \
          -var="project_id=${{ secrets.NTX_GCP_PROJECT_ID }}" \
          -var="region=$GCP_REGION" \
          -var="repo_name=$GCP_REPO_NAME" \

  docker-image-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: infra-gcp-terraform

    steps:
    - uses: actions/checkout@v4

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.NTX_GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.NTX_GCP_SA }}
        export_default_credentials: true

    - name: Authenticate Docker to Artifact Registry
      run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        IMAGE_URI=$GCP_REGION-docker.pkg.dev/${{ secrets.NTX_GCP_PROJECT_ID }}/$GCP_REPO_NAME/$DOCKER_IMAGE_NAME:latest
        docker build -t $IMAGE_URI ./app
        docker push $IMAGE_URI

  deploy:
    runs-on: ubuntu-latest
    needs: docker-image-build

    env: IMAGE_URI=$GCP_REGION-docker.pkg.dev/${{ secrets.NTX_GCP_PROJECT_ID }}/$GCP_REPO_NAME/$DOCKER_IMAGE_NAME:latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.NTX_GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.NTX_GCP_SA }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials autopilot-cluster \
          --region $GCP_REGION --project ${{ secrets.NTX_GCP_PROJECT_ID }}

    - name: Set Image in deployment manifest
      run: |
        sed -i "s|REPLACE_IMAGE|${IMAGE_URI}|g" k8s/deployment.yaml
        sed -i "s|REPLACE_APP|${APP_NAME}|g" k8s/deployment.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml