name: ntx-devops-test-workflow

on:
  push:
    branches: [ "feature" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm install chai@4.3.7
    - run: npm test

  build_oci_image:

    needs: [test]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker OCI Image
      run: |
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
        docker build . --file docker/Dockerfile --tag $APP_NAME:$SHORT_SHA
        echo "APP_IMAGE=$APP_NAME:$SHORT_SHA" >> $GITHUB_ENV
      env:
        APP_NAME: ntx-app
        GITHUB_SHA: ${{ github.sha }}
    - name: Check Docker OCI Image
      run: |
        echo $APP_NAME
        docker images | grep $APP_NAME
