name: ntx-devops-test-workflow

on:
  push:
    branches: [ "feature" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm install chai@4.3.7
    - run: npm test

  build_oci_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker OCI Image
      run: docker build . --file docker/Dockerfile --tag ntx-app:${{ github.sha }} && docker images
